### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'tail'

### ISSUE THREAD

**Issue by sajidrahman** [adbar/trafilatura#16]
`extract` API throws this error while trying to extract content:

```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-333-f77dadd7d5ab> in <module>
----> 1 a = trafilatura.extract(downloaded)
      2 a

~/opt/anaconda2/envs/permpressenv/lib/python3.6/site-packages/trafilatura/core.py in extract(filecontent, url, record_id, no_fallback, include_comments, output_format, csv_output, xml_output, tei_output, tei_validation, target_language, include_tables, include_formatting, date_extraction_params)
    618 
    619     # extract content
--> 620     postbody, temp_text, len_text, sure_thing = extract_content(cleaned_tree, include_tables)
    621 
    622     # compare if necessary

~/opt/anaconda2/envs/permpressenv/lib/python3.6/site-packages/trafilatura/core.py in extract_content(tree, include_tables)
    340         # print(html.tostring(subtree, pretty_print=True, encoding='unicode'))
    341         # extract content
--> 342         processed_elems = [handle_textelem(e, potential_tags) for e in subtree.xpath('.//*')]
    343         # list(filter(None.__ne__, processed_elems))
    344         result_body.extend([e for e in processed_elems if e is not None])

~/opt/anaconda2/envs/permpressenv/lib/python3.6/site-packages/trafilatura/core.py in <listcomp>(.0)
    340         # print(html.tostring(subtree, pretty_print=True, encoding='unicode'))
    341         # extract content
--> 342         processed_elems = [handle_textelem(e, potential_tags) for e in subtree.xpath('.//*')]
    343         # list(filter(None.__ne__, processed_elems))
    344         result_body.extend([e for e in processed_elems if e is not None])

~/opt/anaconda2/envs/permpressenv/lib/python3.6/site-packages/trafilatura/core.py in handle_textelem(element, potential_tags)
    293         if element.tail is not None and not element.tail.isspace():
    294             new_element = etree.Element('p')
--> 295             new_element.text = process_node(element).tail
    296             # new_element.text = handle_textnode(element, comments_fix=False).tail
    297     elif element.tag == 'hi':

AttributeError: 'NoneType' object has no attribute 'tail'
```

Interestingly, contents from the same HTML file can be extracted with `html2text` API. For reproducing this error, try this URL: http://sibenlab.blogspot.com/2018/06/sibenlab-privacy-policy.html

**Comment by adbar** [comment]
Line-breaks without text were indeed a problem, just fixed in 3d8d42d. Thanks!
